#!/bin/bash
#$ -cwd
#$ -o joblog.$JOB_ID
#$ -j y
#$ -l h_rt=0:30:00,h_data=10G
#$ -l gpu


# load the job environment:
. /u/local/Modules/default/init/modules.sh
module load apptainer/1.0.0

# Run singulariy as a single python3 command 
# Container part: apptainer exec pytorch_22.03-py3.sif
# Command: python3 pytorch_gpu.py

apptainer exec --nv pytorch_22.03-py3.sif  python3 pytorch_gpu.py > pytorch_gpu-batch.out
