#!/bin/bash
#$ -cwd
# error = Merged with joblog
#$ -o joblog.$JOB_ID
#$ -j y
#$ -l rh7,h_rt=1:00:00,h_data=10G
#$ -l gpu,exclusive,gpu,RTX2080Ti

# load the job environment:
. /u/local/Modules/default/init/modules.sh
module load singularity/3.7.1

# Run singulariy as a single python3 command 
singularity exec --nv --userns $H2_CONTAINER_LOC/pytorch-21.04-py3.sif  python3 pytorch-gpu.py > pytorch-gpu.out 

